//
// UDUI.RC2 - resources Microsoft Visual C++ does not edit directly
//

#ifdef APSTUDIO_INVOKED
//	#error this file is not editable by Microsoft Visual C++
#endif //APSTUDIO_INVOKED


/////////////////////////////////////////////////////////////////////////////
// Add manually edited resources here...
#define IDR_LEGALCOPYRIGHT_ENUS "Copyright © 1998-2012 3Dconnexion.  All rights reserved."
#define IDR_LEGALCOPYRIGHT_DEDE "Copyright © 1998-2012 3Dconnexion.  Alle Rechte vorbehalten."
#define IDR_LEGALCOPYRIGHT_FRFR "Copyright © 1998-2012 3Dconnexion"
#define IDR_LEGALCOPYRIGHT_JPJP "Copyright © 1998-2012 3Dconnexion"
#define IDR_LEGALCOPYRIGHT_CHCH "Copyright © 1998-2012 3Dconnexion"

#define IDR_3DXWINCORE_PRODUCTVERSION_STR "17, 0, 20, 0"
#define IDR_3DXWINCORE_PRODUCTVERSION_NUM 17,0,20,0

#define IDR_3DXSERVICE_FILEVERSION_STR "17, 0, 20, 0"
#define IDR_3DXSERVICE_FILEVERSION_NUM 17,0,20,0

#define IDR_3DXSERVICE_ENUS_FILEVERSION_STR "17, 0, 20, 0"
#define IDR_3DXSERVICE_ENUS_FILEVERSION_NUM 17,0,20,0

#define IDR_3DXSERVICE_DEDE_FILEVERSION_STR "17, 0, 20, 0"
#define IDR_3DXSERVICE_DEDE_FILEVERSION_NUM 17,0,20,0

#define IDR_3DXSERVICE_FRFR_FILEVERSION_STR "17, 0, 20, 0"
#define IDR_3DXSERVICE_FRFR_FILEVERSION_NUM 17,0,20,0

#define IDR_3DXSERVICE_JPJP_FILEVERSION_STR "17, 0, 20, 0"
#define IDR_3DXSERVICE_JPJP_FILEVERSION_NUM 17,0,20,0

#define IDR_3DXSERVICE_CHCH_FILEVERSION_STR "17, 0, 20, 0"
#define IDR_3DXSERVICE_CHCH_FILEVERSION_NUM 17,0,20,0

// (This isn't used by the 3DxConfig project.  It needs to be change manually. (AssemblyInfo.cs))
#define IDR_3DXCONFIG_FILEVERSION_STR "1, 0, 16, 0"
#define IDR_3DXCONFIG_FILEVERSION_NUM 1,0,16,0

// (I don't think 3DxConfig has resources that use these)
#define IDR_3DXCONFIG_ENUS_FILEVERSION_STR "1, 0, 16, 0"
#define IDR_3DXCONFIG_ENUS_FILEVERSION_NUM 1,0,16,0

#define IDR_3DXCONFIG_DEDE_FILEVERSION_STR "1, 0, 16, 0"
#define IDR_3DXCONFIG_DEDE_FILEVERSION_NUM 1,0,16,0

#define IDR_3DXCONFIG_FRFR_FILEVERSION_STR "1, 0, 16, 0"
#define IDR_3DXCONFIG_FRFR_FILEVERSION_NUM 1,0,16,0

#define IDR_3DXCONFIG_JPJP_FILEVERSION_STR "1, 0, 16, 0"
#define IDR_3DXCONFIG_JPJP_FILEVERSION_NUM 1,0,16,0

#define IDR_3DXCONFIG_CHCH_FILEVERSION_STR "1, 0, 16, 0"
#define IDR_3DXCONFIG_CHCH_FILEVERSION_NUM 1,0,16,0

#define IDR_3DXHOME_FILEVERSION_STR "1, 0, 11, 0"
#define IDR_3DXHOME_FILEVERSION_NUM 1,0,11,0

#define IDR_HIDDEV_FILEVERSION_STR "10, 1, 0, 0"
#define IDR_HIDDEV_FILEVERSION_NUM 10,1,0,0

#define IDR_S80TRANS_FILEVERSION_STR "3, 8, 13, 0"
#define IDR_S80TRANS_FILEVERSION_NUM 3,8,13,0

#define IDR_MWMTRANS_FILEVERSION_STR "2, 8, 13, 0"
#define IDR_MWMTRANS_FILEVERSION_NUM 2,8,13,0

#define IDR_KMJTRANS_FILEVERSION_STR "3, 0, 16, 0"
#define IDR_KMJTRANS_FILEVERSION_NUM 3,0,16,0

#define IDR_JET_FILEVERSION_STR "1, 1, 13, 0"
#define IDR_JET_FILEVERSION_NUM 1,1,13,0

#define IDR_CUBE3D_FILEVERSION_STR "1, 1, 13, 0"
#define IDR_CUBE3D_FILEVERSION_NUM 1,1,13,0

#define IDR_CHICKEN_FILEVERSION_STR "1, 1, 13, 0"
#define IDR_CHICKEN_FILEVERSION_NUM 1,1,13,0

#define IDR_BICYCLEDI_FILEVERSION_STR "10, 1, 13, 0"
#define IDR_BICYCLEDI_FILEVERSION_NUM 10,1,13,0

#define IDR_PUZZLE_FILEVERSION_STR "2, 0, 13, 0"
#define IDR_PUZZLE_FILEVERSION_NUM 2,0,13,0

#define IDR_3DXTEST_FILEVERSION_STR "1, 0, 3, 0"
#define IDR_3DXTEST_FILEVERSION_NUM 1,0,3,0

#define IDR_3DXTSTMFC_FILEVERSION_STR "1, 0, 3, 0"
#define IDR_3DXTSTMFC_FILEVERSION_NUM 1,0,3,0

#define IDR_CITYFLY_FILEVERSION_STR "1, 0, 3, 0"
#define IDR_CITYFLY_FILEVERSION_NUM 1,0,3,0

#define IDR_WIDGET_FILEVERSION_STR "1, 0, 3, 0"
#define IDR_WIDGET_FILEVERSION_NUM 1,0,3,0

#define IDR_LAUNCH3DXVIEWER_FILEVERSION_STR "1, 1, 13, 0"
#define IDR_LAUNCH3DXVIEWER_FILEVERSION_NUM 1,1,13,0

#define IDR_SIAPP_FILEVERSION_STR "4, 0, 13, 0"
#define IDR_SIAPP_FILEVERSION_NUM 4,0,13,0

#define IDR_SPWINI_FILEVERSION_STR "11, 0, 14, 0"
#define IDR_SPWINI_FILEVERSION_NUM 11,0,14,0

#define IDR_CATIADLL_FILEVERSION_STR "1, 0, 12, 0"
#define IDR_CATIADLL_FILEVERSION_NUM 1,0,12,0

#define IDR_MSOFFICEDLL_FILEVERSION_STR "1, 0, 12, 0"
#define IDR_MSOFFICEDLL_FILEVERSION_NUM 1,0,12,0

#define IDR_WIN32UTILSDLL_FILEVERSION_STR "1, 0, 3, 0"
#define IDR_WIN32UTILSDLL_FILEVERSION_NUM 1,0,3,0

/////////////////////////////////////////////////////////////////////////////
